/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const InviteToken = IDL.Record({
  'boundPrincipal' : IDL.Opt(IDL.Principal),
  'token' : IDL.Text,
  'usageCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'issuedAt' : Time,
  'issuedBy' : IDL.Principal,
  'maxUses' : IDL.Nat,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const HotelContact = IDL.Record({
  'whatsapp' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
});
export const SubscriptionStatus = IDL.Variant({
  'paid' : IDL.Null,
  'test' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const PaymentMethod = IDL.Record({
  'name' : IDL.Text,
  'details' : IDL.Text,
});
export const RoomView = IDL.Record({
  'id' : IDL.Nat,
  'pricePerNight' : IDL.Nat,
  'hotelId' : IDL.Principal,
  'roomNumber' : IDL.Text,
  'currency' : IDL.Text,
  'pictures' : IDL.Vec(IDL.Text),
  'roomType' : IDL.Text,
});
export const HotelDataView = IDL.Record({
  'id' : IDL.Principal,
  'active' : IDL.Bool,
  'contact' : HotelContact,
  'mapLink' : IDL.Text,
  'bookings' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'subscriptionStatus' : SubscriptionStatus,
  'address' : IDL.Text,
  'location' : IDL.Text,
  'paymentMethods' : IDL.Vec(PaymentMethod),
  'rooms' : IDL.Vec(RoomView),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateHotelDirectly' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'consumeInviteToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createInviteToken' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Principal)],
      [InviteToken],
      [],
    ),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerHotelProfile' : IDL.Func([], [IDL.Opt(HotelDataView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHotelProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(HotelDataView)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getInviteTokens' : IDL.Func([], [IDL.Vec(InviteToken)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getValidHotelInviteTokens' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerHotelActivated' : IDL.Func([], [IDL.Bool], ['query']),
  'isHotelActiveByDirectActivation' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'isValidHotelInviteToken' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const InviteToken = IDL.Record({
    'boundPrincipal' : IDL.Opt(IDL.Principal),
    'token' : IDL.Text,
    'usageCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'issuedAt' : Time,
    'issuedBy' : IDL.Principal,
    'maxUses' : IDL.Nat,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const HotelContact = IDL.Record({
    'whatsapp' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
  });
  const SubscriptionStatus = IDL.Variant({
    'paid' : IDL.Null,
    'test' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const PaymentMethod = IDL.Record({ 'name' : IDL.Text, 'details' : IDL.Text });
  const RoomView = IDL.Record({
    'id' : IDL.Nat,
    'pricePerNight' : IDL.Nat,
    'hotelId' : IDL.Principal,
    'roomNumber' : IDL.Text,
    'currency' : IDL.Text,
    'pictures' : IDL.Vec(IDL.Text),
    'roomType' : IDL.Text,
  });
  const HotelDataView = IDL.Record({
    'id' : IDL.Principal,
    'active' : IDL.Bool,
    'contact' : HotelContact,
    'mapLink' : IDL.Text,
    'bookings' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'subscriptionStatus' : SubscriptionStatus,
    'address' : IDL.Text,
    'location' : IDL.Text,
    'paymentMethods' : IDL.Vec(PaymentMethod),
    'rooms' : IDL.Vec(RoomView),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateHotelDirectly' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'consumeInviteToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createInviteToken' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Principal)],
        [InviteToken],
        [],
      ),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerHotelProfile' : IDL.Func([], [IDL.Opt(HotelDataView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHotelProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(HotelDataView)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getInviteTokens' : IDL.Func([], [IDL.Vec(InviteToken)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getValidHotelInviteTokens' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerHotelActivated' : IDL.Func([], [IDL.Bool], ['query']),
    'isHotelActiveByDirectActivation' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isValidHotelInviteToken' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };