/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingQuery {
  'status' : [] | [BookingStatus],
  'hotelId' : [] | [Principal],
  'maxPrice' : [] | [bigint],
  'toDate' : [] | [bigint],
  'fromDate' : [] | [bigint],
  'minPrice' : [] | [bigint],
}
export interface BookingQueryResult {
  'bookings' : Array<BookingRequest>,
  'totalCount' : bigint,
}
export interface BookingRequest {
  'id' : bigint,
  'status' : BookingStatus,
  'checkIn' : bigint,
  'userId' : Principal,
  'hotelId' : [] | [Principal],
  'paymentProof' : [] | [string],
  'currency' : string,
  'timestamp' : bigint,
  'checkOut' : bigint,
  'roomId' : bigint,
  'totalPrice' : bigint,
  'guests' : bigint,
}
export type BookingStatus = { 'canceled' : null } |
  { 'booked' : null } |
  { 'checkedIn' : null } |
  { 'pendingTransfer' : null } |
  { 'paymentFailed' : null };
export interface HotelContact {
  'whatsapp' : [] | [string],
  'email' : [] | [string],
}
export interface HotelDataView {
  'id' : Principal,
  'active' : boolean,
  'contact' : HotelContact,
  'mapLink' : string,
  'bookings' : Array<bigint>,
  'name' : string,
  'subscriptionStatus' : SubscriptionStatus,
  'address' : string,
  'location' : string,
  'paymentMethods' : Array<PaymentMethod>,
  'rooms' : Array<RoomView>,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface InviteToken {
  'boundPrincipal' : [] | [Principal],
  'token' : string,
  'usageCount' : bigint,
  'isActive' : boolean,
  'issuedAt' : Time,
  'issuedBy' : Principal,
  'maxUses' : bigint,
}
export interface PaymentMethod { 'name' : string, 'details' : string }
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface RoomQuery {
  'hotelId' : [] | [Principal],
  'maxPrice' : [] | [bigint],
  'availableOnly' : [] | [boolean],
  'minPrice' : [] | [bigint],
  'roomType' : [] | [string],
}
export interface RoomView {
  'id' : bigint,
  'pricePerNight' : bigint,
  'hotelId' : Principal,
  'roomNumber' : string,
  'currency' : string,
  'pictures' : Array<string>,
  'roomType' : string,
}
export type SubscriptionStatus = { 'paid' : null } |
  { 'test' : null } |
  { 'unpaid' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateHotelOwner' : ActorMethod<[Principal], undefined>,
  'addPaymentMethod' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'consumeInviteToken' : ActorMethod<[string], undefined>,
  'createBooking' : ActorMethod<
    [Principal, bigint, bigint, bigint, bigint, string],
    bigint
  >,
  'createInviteToken' : ActorMethod<[bigint, [] | [Principal]], string>,
  'createMockBooking' : ActorMethod<
    [[] | [Principal], bigint, bigint, bigint, bigint, bigint, string],
    undefined
  >,
  'createRoom' : ActorMethod<
    [string, string, bigint, string, Array<string>],
    bigint
  >,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getBookings' : ActorMethod<[BookingQuery], BookingQueryResult>,
  'getCallerHotelProfile' : ActorMethod<[], [] | [HotelDataView]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHotels' : ActorMethod<[], Array<HotelDataView>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getInviteTokens' : ActorMethod<[], Array<InviteToken>>,
  'getRooms' : ActorMethod<[RoomQuery], Array<RoomView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeMeAdmin' : ActorMethod<[], undefined>,
  'recordStayCompletion' : ActorMethod<[bigint], undefined>,
  'removePaymentMethod' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setHotelActiveStatus' : ActorMethod<[Principal, boolean], undefined>,
  'setHotelSubscriptionStatus' : ActorMethod<
    [Principal, SubscriptionStatus],
    undefined
  >,
  'setPaymentProof' : ActorMethod<[bigint, string], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateHotelProfile' : ActorMethod<
    [string, string, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateRoom' : ActorMethod<
    [bigint, string, string, bigint, string, Array<string>],
    undefined
  >,
  'validateInviteToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];